### PR TITLE
New tools: NetImpute

### PR DESCRIPTION
**Pull request by iustin94**
Added NetImpute to database.

### CODE REVIEW

**Comment by lazappi** [comment]
Thanks @iustin94, this looks better 👍! Can I just get you to change the license to "GPL-3.0" rather than the full name? You can do this using `./scrnatools update NetImpute` and selecting "License" from the menu.

**Comment by iustin94** [comment]
Done :+1:

**Comment by lazappi** [comment]
Thanks!

Just a note for future reference. We need to be a bit careful about commit messages because anything that starts with "New tool" or "Update" get automatically tweeted. As long as you follow the templates everything should be fine.

**Comment by iustin94** [comment]
Ah ok, didn't know that just saved what the autocommit message sugested.

**Pull request merged**
